# Generated by Django 5.2.1 on 2025-05-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users_create_date_users_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
