# Generated by Django 5.2.1 on 2025-05-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_categories_options_alter_posts_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='category',
        ),
        migrations.AddField(
            model_name='posts',
            name='categories',
            field=models.ManyToManyField(to='blog.categories'),
        ),
    ]
